server:
  port: 8082
logging:
  level:
    org.springframework.security: DEBUG
    com.example.EdaFon_Restaurants: TRACE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurants?currentSchema=public
    username: postgres
    password: Boxing2003
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          default_schema: public
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: EdaFonJWTEdaFonJWTEdaFonJWTEdaFonJWT

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
